### ISSUE TITLE
'setuptools' distribution was not found

### ISSUE THREAD

**Issue by AndyBarnett** [rileydakota/valheim-ecs-fargate-cdk#25]
After deploying, my services keeps pending then stopping over and over again. Each time it stops for the same reason. I check the Event log and it says:
"pkg_resources.DistributionNotFound: The 'setuptools' distribution was not found and is required by supervisor". I'm using node 17.5.0 but this happened on an earlier version too.

full log here:
2022-02-17T23:54:39.940+00:00    INFO - Setting uid:gid of valheim to 0:0

2022-02-17T23:54:41.237+00:00    INFO - Setting timezone Etc/UTC

2022-02-17T23:54:41.237+00:00    INFO - Setting up syslogd - logging to stdout

2022-02-17T23:54:41.313+00:00    Traceback (most recent call last):

2022-02-17T23:54:41.313+00:00    File "/usr/local/bin/supervisord", line 6, in <module>

2022-02-17T23:54:41.313+00:00    from pkg_resources import load_entry_point

2022-02-17T23:54:41.313+00:00    File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 3191, in <module>

2022-02-17T23:54:41.313+00:00    @_call_aside

2022-02-17T23:54:41.313+00:00    File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 3175, in _call_aside

2022-02-17T23:54:41.313+00:00    f(*args, **kwargs)

2022-02-17T23:54:41.313+00:00    File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 3204, in _initialize_master_working_set

2022-02-17T23:54:41.313+00:00    working_set = WorkingSet._build_master()

2022-02-17T23:54:41.313+00:00    File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 583, in _build_master

2022-02-17T23:54:41.313+00:00    ws.require(requires)

2022-02-17T23:54:41.313+00:00    File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 900, in require

2022-02-17T23:54:41.313+00:00    needed = self.resolve(parse_requirements(requirements))

2022-02-17T23:54:41.313+00:00    File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 786, in resolve

2022-02-17T23:54:41.313+00:00    raise DistributionNotFound(req, requirers)

2022-02-17T23:54:41.313+00:00    pkg_resources.DistributionNotFound: The 'setuptools' distribution was not found and is required by supervisor

**Comment by AndyBarnett** [comment]
whoops, I forgot to bootstrap as per the readme. After that, even though there were more errors, I managed to successfully deploy and connect to the server
